# valores especificos del ambiente production para appointments-service
image:
  repository: ghcr.io/aidaorantes9/sa-practica-appointments-service
  tag: "v0.0.0-init"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-pull-secret

replicaCount: 2
autoscaling:
  enabled: false
