# valores especificos del ambiente staging para artists-service
image:
  repository: ghcr.io/aidaorantes9/sa-practica-artists-service
  tag: "v0.0.0-init"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-pull-secret

replicaCount: 1
autoscaling:
  enabled: false
