apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appointments-service-production
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://github.com/aidaorantes9/Practicas-SA-B-202100239.git
      targetRevision: main
      path: P5/charts/sa-platform/charts/appointments-service
      helm:
        parameters:
          - name: sharedConfigMapName
            value: "sa-p8-app-config"
          - name: sharedSecretName
            value: "sa-p8-app-secrets"
        valueFiles:
          - $values/apps/appointments-service/values-production.yaml
    - repoURL: https://github.com/aidaorantes9/P8_GITOPS_202100239.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=false
