apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-service-staging
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/aidaorantes9/Practicas-SA-B-202100239.git
      targetRevision: main
      path: P5/charts/sa-platform/charts/notification-service
      helm:
        parameters:
          - name: sharedConfigMapName
            value: "sa-p8-app-config"
          - name: sharedSecretName
            value: "sa-p8-app-secrets"
        valueFiles:
          - $values/apps/notification-service/values-staging.yaml
    - repoURL: https://github.com/aidaorantes9/P8_GITOPS_202100239.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
