# valores especificos del ambiente production para notification-service
image:
  repository: ghcr.io/aidaorantes9/sa-practica-notification-service
  tag: "v0.1.5"
  pullPolicy: Always


replicaCount: 1
autoscaling:
  enabled: false
