# valores especificos del ambiente production para api-gateway
image:
  repository: ghcr.io/aidaorantes9/sa-practica-api-gateway
  tag: "v0.1.5"
  pullPolicy: Always


replicaCount: 2
autoscaling:
  enabled: false
