# valores especificos del ambiente production para api-gateway
image:
  repository: ghcr.io/aidaorantes9/sa-practica-api-gateway
  tag: "v0.0.0-init"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-pull-secret

replicaCount: 2
autoscaling:
  enabled: false
